### ISSUE TITLE
Support Creating apklib Android Libraries

### ISSUE THREAD

**Issue by epabst** [jberkel/android-plugin#130]
I see support for having a dependency on an .apklib artifact, but I don't see any support to be able to create one.  I have a project called scala-android-crud (aka scrud-android) that I'm converting to use sbt, but it is using android-maven-plugin to create an .apklib.  I really want to move to sbt but this is blocking me.  Please help.

**Comment by appamatto** [comment]
https://github.com/jberkel/android-plugin/pull/143

**Comment by zbsz** [comment]
Hi, I'm trying to use the aplibPackage task, but it doesn't work (or actually I don't really know how to do this)
Is there some exaple project using this feature somewhere?

I added this to settings:
addArtifact(Artifact("mylib", "apklib", "apklib"), apklibPackage in Android).settings

When executing:  sbt publish  (tried also sbt publish-local and sbt android:apklib-package with the same result)
I get and exception:

java.lang.RuntimeException: No mapping for {project_path}/src/main/assets
        at scala.sys.package$.error(package.scala:27)
        at scala.Predef$.error(Predef.scala:123)
        at sbt.Mapper$$anonfun$fail$1.apply(PathMapper.scala:34)
        at sbt.Mapper$$anonfun$fail$1.apply(PathMapper.scala:34)
        at sbt.Alternatives$$anon$1$$anonfun$$bar$1$$anonfun$apply$3.apply(PathMapper.scala:101)
        at sbt.Alternatives$$anon$1$$anonfun$$bar$1$$anonfun$apply$3.apply(PathMapper.scala:101)
        at scala.Option.orElse(Option.scala:218)
        at sbt.Alternatives$$anon$1$$anonfun$$bar$1.apply(PathMapper.scala:101)
        at sbt.Alternatives$$anon$1$$anonfun$$bar$1.apply(PathMapper.scala:101)
        at sbt.PathFinder$$anonfun$x$1.apply(Path.scala:155)
        at sbt.PathFinder$$anonfun$x$1.apply(Path.scala:155)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:239)
        at scala.collection.mutable.ArrayBuffer.flatMap(ArrayBuffer.scala:47)
        at sbt.PathFinder.x(Path.scala:155)
        at AndroidBase$$anonfun$apklibPackageTask$1.apply(AndroidBase.scala:70)
        at AndroidBase$$anonfun$apklibPackageTask$1.apply(AndroidBase.scala:63)
        at sbt.Scoped$$anonfun$hf7$1.apply(Structure.scala:583)
        at sbt.Scoped$$anonfun$hf7$1.apply(Structure.scala:583)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$5.work(System.scala:71)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:238)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)

**Comment by PkmX** [comment]
@zbsz: Check out my pull request cac6e39, there is a typo in `apklibPackageTask`.

**Comment by zbsz** [comment]
That fixed my problem, thanks.
